### ISSUE TITLE
Getting started instructions not working? Got 404 error

### ISSUE THREAD

**Issue by vdallaire** [ulaval/modul-website#1]
In the project folder, run the following command: npm link modul-components. This will create a symbolic link between both projects.

I am getting this error : 

npm ERR! code E404
npm ERR! 404 Not Found: modul-components@latest

**Comment by vdallaire** [comment]
The following command seems to work : npm link @ulaval/modul-components.

I had also to change the devDependencies to @ulaval/modul-components in package.json file to be able to run npm install.

But I got multiple compilation errors on npm run dev. Here they are.

ERROR in ./src/app/main.ts
Module not found: Error: Can't resolve 'modul-components/dist/buttons' in 'C:\modul\modul-website\src\app'
 @ ./src/app/main.ts 6:0-52
 @ multi (webpack)-dev-server/client?http://localhost:8082 ./src/app/main.ts

ERROR in ./src/app/main.ts
Module not found: Error: Can't resolve 'modul-components/dist/text' in 'C:\modul\modul-website\src\app'
 @ ./src/app/main.ts 7:0-46
 @ multi (webpack)-dev-server/client?http://localhost:8082 ./src/app/main.ts

ERROR in ./src/app/main.ts
Module not found: Error: Can't resolve 'modul-components/dist/services' in 'C:\modul\modul-website\src\app'
 @ ./src/app/main.ts 8:0-49
 @ multi (webpack)-dev-server/client?http://localhost:8082 ./src/app/main.ts

ERROR in ./src/app/components/libs/component.ts
Module not found: Error: Can't resolve 'modul-components/dist/services' in 'C:\modul\modul-website\src\app\components\libs'
 @ ./src/app/components/libs/component.ts 22:0-62
 @ ./src/app/router.ts
 @ ./src/app/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:8082 ./src/app/main.ts

ERROR in ./src/app/router.ts
Module not found: Error: Can't resolve 'modul-components/dist/meta' in 'C:\modul\modul-website\src\app'
 @ ./src/app/router.ts 9:0-46
 @ ./src/app/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:8082 ./src/app/main.ts

ERROR in ./src/app/store/actions.ts
Module not found: Error: Can't resolve 'modul-components/dist/meta' in 'C:\modul\modul-website\src\app\store'
 @ ./src/app/store/actions.ts 3:0-46
 @ ./src/app/store/index.ts
 @ ./src/app/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:8082 ./src/app/main.ts

ERROR in ./src/app/store/mutations.ts
Module not found: Error: Can't resolve 'modul-components/dist/meta' in 'C:\modul\modul-website\src\app\store'
 @ ./src/app/store/mutations.ts 1:0-46
 @ ./src/app/store/index.ts
 @ ./src/app/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:8082 ./src/app/main.ts

ERROR in ./src/app/store/actions.ts
Module not found: Error: Can't resolve 'modul-components/dist/meta-fr' in 'C:\modul\modul-website\src\app\store'
 @ ./src/app/store/actions.ts 11:15-18:10 12:20-60
 @ ./src/app/store/index.ts
 @ ./src/app/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:8082 ./src/app/main.ts

**Comment by simardo** [comment]
modul-website is still in development (no version released yet). The master branch doesn't match the modul-components master branch (which has a few releases now). Stay tuned. Documentation should be updated though.
