### ISSUE TITLE
Unable to open any type of modal windows

### ISSUE THREAD

**Issue by jipigi** [ulaval/modul-website#24]
### To reproduce
1. Go to /composants/fenetres/m-popup/portrait
2. Clic the « Ouvrir » button 

### Expected behaviour
The modal window should open.

### Observed behaviour
Nothing happen : https://www.screencast.com/t/SMjw5myaMRpa

We have the same problem with all window components :
- m-popup
- m-sidebar
- m-dialog
- m-modal
- m-tooltip
- m-menu
- m-popper

**Comment by setur52** [comment]
Solved!
