### ISSUE TITLE
Empty dropdwon on component page

### ISSUE THREAD

**Issue by jipigi** [ulaval/modul-website#25]
### To reproduce
- Go to a component list page (« Composants > Formulaires » or « Composants > Contenus »).
OR
- Go to a component page (« Composants > Formulaires > Bouton » or « Composants > Contenus > Acordéon »).
- Clic on the dropdown.

See https://www.screencast.com/t/BIy5rydwNAi.

### Observed behaviour
- Dropdown is empty.

### Expected behaviour
- Dropdown should list every components in the section.

**Comment by setur52** [comment]
Seem to be solved!
