### ISSUE TITLE
Pattern generating errors

### ISSUE THREAD

**Issue by guimou** [ulaval/modul-website#3]
File reference https://github.com/ulaval/modul-website/blob/58b07ea71c1ec37c864c7b28b8840f577e45c2ad/conf/stylelint.json#L9

Are you sure of this pattern?

It generates lots of error at compilation...

**Comment by simardo** [comment]
Pattern used in modul-website: `"scss/dollar-variable-pattern": "^modul-"`
Pattern used in modul-components: `"scss/dollar-variable-pattern": "^m-"`
Looking why the default pattern causes problems since modul-website doesn't have the same pattern than modul-components anyway.

**Comment by simardo** [comment]
Using the predefined rule in the template (^foo):
`$foo-button--color: #000;` - valid
`$foo--color: $m-color--interactive !default;` - valid
`$m-button--color: $m-color--interactive !default;` ×  Expected $ variable name to match specified pattern
`$m-button--color: #000;` ×  Expected $ variable name to match specified pattern

The rule works fine, but I will modify the CLI template generator to set the rule to the project name. If you name the project "foo-bar", the rule will be:

`"scss/dollar-variable-pattern": "^foo-bar"`.

Developers will need to declare sass variables like this:
`$foo-bar--color: $m-color--interactive !default;`
`$foo-bar--color: #000;`
`$foo-bar-button--color: #000;`
`$foo-bar--color: $m-color--interactive !default;`
`$foo-bar--color: $m-color--interactive !default;`
`$foo-bar--color: $m-color--interactive !default;`
